name: "Pipeline: Release"
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out latest code
        uses: actions/checkout@v5

      - name: Install tinygo and dependencies
        run: |
          wget https://github.com/tinygo-org/tinygo/releases/download/v0.40.1/tinygo_0.40.1_amd64.deb
          sudo dpkg -i tinygo_0.40.1_amd64.deb
          sudo apt install -y binaryen

      - name: Download dependencies
        run: go mod download

      - name: Build plugin
        run: tinygo build -o plugin.wasm -target wasip1 -buildmode=c-shared .

      - name: Create packate
        run: zip brainz.ndp plugin.wasm manifest.json

      - name: Generate draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: brainz.ndp
          generate_release_notes: true